### ISSUE TITLE
Spin Buttons visible on Firefox

### ISSUE THREAD

**Issue by fernandosavio** [ZestfulNation/vue-number-input-spinner#9]
Hi,
I've looked the code and noticed you hide the native buttons on Webkit based browser, but not on Firefox.
Any problem with [`-moz-appeareance: textfield;`](https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-appearance) ?

Just add a line in `&__input` rules:

```css
&__input {
    /* ... */
    -moz-appearance: textfield; /* :) */

    &::-webkit-outer-spin-button,
    &::-webkit-inner-spin-button {
        -webkit-appearance: none;
    }
}
```

Cheers.
